### ISSUE TITLE
原数据集原始权重复现问题

### ISSUE THREAD

**Issue by ccy2248** [Xinyu-Xiang/DIVFusion#16]
作者这里为什么用了提供的原始数据集和权重，最后融合的图像第一张必定乱码，第二张及以后左边的内容被缝合到右边去了
![1](https://github.com/user-attachments/assets/7dc657f7-7506-474b-b9e1-1f689a5a27d6)
![2](https://github.com/user-attachments/assets/99be338b-1106-4463-9229-e3f63780b7df)

**Comment by Xinyu-Xiang** [comment]
这个可能是在数据集载入过程顺序出现了替换，可以检查一下数据载入的是否是成对图像

**Comment by ccy2248** [comment]
> 这个可能是在数据集载入过程顺序出现了替换，可以检查一下数据载入的是否是成对图像

好的感谢作者的回复，我在检查了使用的是您提供的测试集，这里按照您所说的检查了load加载图像的步骤，在输入模型生成前我确定是完好且成对出现的图片，这里在扔进模型之后就发生了这样的问题
1、我进行了多次测试改变batch查看了多张图片，期间我设置的batch为1时也是这样，发现每次都是第一张必定乱码
2、后续第二张开始，就是生成的图片内容（不包括颜色信息）都是左边的内容被截取到右边

这个我检查了好久，请问作者对这个问题有什么思路吗（不过还是谢谢作者回过来能耐心回复这项目的问题：）））

**Comment by ccy2248** [comment]
> 这个可能是在数据集载入过程顺序出现了替换，可以检查一下数据载入的是否是成对图像

作者现在这个代码可能不能用cpu跑了，因为现在目前tensorflow版本中有好多方法已经过时不再维护，我现在现在用cpu复现会出现上述的情况，这几天我找了一个比较老的板子进行cuda加速这个问题完全解决了，这里我的情况仅供参考，感谢作者您为开源代码做出的付出
